import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Share Panda",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ToastContainer position="top-center" theme="dark" />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
